### PR TITLE
[MRG] Update spectral colormap to viridis

### PR DESCRIPTION
**Pull request by glemaitre**

### CODE REVIEW

**Comment by amueller** [comment]
should actually be tab10 for categorical, right? (though you need to make sure they are blue and orange not dark blue and light blue, but I think the way I did it it's correct).

**Comment by glemaitre** [comment]
> not dark blue and light blue

Just by changing to Tab10 it was those color :)

**Comment by amueller** [comment]
really? by using ``cm=plt.cm.tag10`` or by using ``c=plt.cm.tab10(y)``? The latter should work.

**Comment by glemaitre** [comment]
True (divide by 2 was wrong). The rendering is fine now.

**Pull request merged**
