### PR TITLE
[MRG] MAINT: Update notebook 7

### PR DESCRIPTION
**Pull request by glemaitre**
- [x] Fix `digits_plot.py`
- [x] Update the preprocessing with QuantileTransformer and PowerTransformer?

### CODE REVIEW

**Comment by amueller** [comment]
why was that figure followed by imshow? that makes no sense...

Have you checked on the dataset downloads?

**Comment by glemaitre** [comment]
The images corresponds to the first and second component. The issue is that `matshow` apparently create a figure as well while `imshow` will plot the figure in the `gca`. Removing `plt.figure()` and keeping `matshow(...)` (and putting `plt.title` after) will lead to a similar result.

> Have you checked on the dataset downloads?

If you refer to the fetcher, not yet. I am planning to take my day of tomorrow for review and focusing to address the issue. I finish up the "ignore NaNs in scaler" (if you wish to review some stuff :))

**Comment by amueller** [comment]
> The images corresponds to the first and second component. The issue is that matshow apparently create a figure as well while imshow will plot the figure in the gca. Removing plt.figure() and keeping matshow(...) (and putting plt.title after) will lead to a similar result.

I know that's why I was confused why there was both matshow and figure.

**Comment by amueller** [comment]
I wish to review lots of stuff, the question is whether can get away with reviewing PRs instead of reviewing papers, books and student reports ;)

**Comment by amueller** [comment]
hm travis is not enabled right now :-/ heading out now and giving you admin rights (or trying to)

**Comment by glemaitre** [comment]
> hm travis is not enabled right now :-/ heading out now and giving you admin rights (or trying to)

I still don't have the admin rights to enable travis. At least, I enable on my forks to not break stuff.

**Comment by amueller** [comment]
ci should be good now.

**Pull request merged**
